# Generated by Django 4.0 on 2022-01-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclassstudent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Student Email'),
        ),
    ]
