# Generated by Django 4.0 on 2022-01-28 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myclassstudent',
            name='email',
        ),
        migrations.AddField(
            model_name='myclassstudent',
            name='badge',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='myclassstudent',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.classroom'),
        ),
    ]
