# Generated by Django 4.0 on 2022-01-28 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_myclassstudent_email_myclassstudent_badge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myclassstudent',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='myclassstudent',
            name='last_name',
        ),
    ]
