# Generated by Django 4.0 on 2022-02-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_attendees_remove_event_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myclassstudent',
            name='teacher',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
