# Generated by Django 4.0 on 2022-02-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_myclassstudent_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclassstudent',
            name='teacher',
            field=models.CharField(max_length=60),
        ),
    ]
