# Generated by Django 4.0 on 2022-02-15 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_myclassstudent_lecturer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyClassStudent',
        ),
    ]
