# Generated by Django 4.0 on 2022-02-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_myclassstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lesson',
            field=models.CharField(default='Intro', max_length=30),
        ),
    ]
