# Generated by Django 4.0 on 2022-02-15 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_event_lesson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
