# Generated by Django 4.0 on 2022-02-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lesson',
            field=models.IntegerField(verbose_name='Lesson Number'),
        ),
    ]
