# Generated by Django 4.0 on 2022-02-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_alter_event_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reward',
            field=models.IntegerField(default='1', verbose_name='Badge'),
        ),
    ]
